# Generated by Django 4.0.3 on 2022-05-15 10:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_shopuser_activation_key_expires_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuserprofile',
            old_name='aboutMe',
            new_name='about_me',
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 10, 27, 47, 399425, tzinfo=utc)),
        ),
    ]
